// Temporary stub for Firebase options. Replace with generated file:
// Run: flutterfire configure --project <YOUR_FIREBASE_PROJECT_ID> --out lib/firebase_options.dart

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'dart:io' show Platform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (Platform.isAndroid) {
      // Placeholder values. Replace with real values generated by FlutterFire.
      return const FirebaseOptions(
        apiKey: 'REPLACE_ME',
        appId: 'REPLACE_ME',
        messagingSenderId: 'REPLACE_ME',
        projectId: 'REPLACE_ME',
        storageBucket: 'REPLACE_ME',
        androidClientId: null,
        iosClientId: null,
        iosBundleId: null,
      );
    } else if (Platform.isIOS || Platform.isMacOS) {
      return const FirebaseOptions(
        apiKey: 'REPLACE_ME',
        appId: 'REPLACE_ME',
        messagingSenderId: 'REPLACE_ME',
        projectId: 'REPLACE_ME',
        storageBucket: 'REPLACE_ME',
        iosClientId: 'REPLACE_ME',
        iosBundleId: 'REPLACE_ME',
      );
    } else if (Platform.isWindows) {
      return const FirebaseOptions(
        apiKey: 'REPLACE_ME',
        appId: 'REPLACE_ME',
        messagingSenderId: 'REPLACE_ME',
        projectId: 'REPLACE_ME',
        storageBucket: 'REPLACE_ME',
      );
    } else if (Platform.isLinux) {
      return const FirebaseOptions(
        apiKey: 'REPLACE_ME',
        appId: 'REPLACE_ME',
        messagingSenderId: 'REPLACE_ME',
        projectId: 'REPLACE_ME',
        storageBucket: 'REPLACE_ME',
      );
    } else {
      // Web or other platforms
      return const FirebaseOptions(
        apiKey: 'REPLACE_ME',
        appId: 'REPLACE_ME',
        messagingSenderId: 'REPLACE_ME',
        projectId: 'REPLACE_ME',
        storageBucket: 'REPLACE_ME',
      );
    }
  }
}
